set(_CATKIN_CURRENT_PACKAGE "wwpcamera")
set(wwpcamera_VERSION "0.0.0")
set(wwpcamera_MAINTAINER "guilherme <guilherme@todo.todo>")
set(wwpcamera_PACKAGE_FORMAT "2")
set(wwpcamera_BUILD_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(wwpcamera_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(wwpcamera_BUILDTOOL_DEPENDS "catkin")
set(wwpcamera_BUILDTOOL_EXPORT_DEPENDS )
set(wwpcamera_EXEC_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(wwpcamera_RUN_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(wwpcamera_TEST_DEPENDS )
set(wwpcamera_DOC_DEPENDS )
set(wwpcamera_URL_WEBSITE "")
set(wwpcamera_URL_BUGTRACKER "")
set(wwpcamera_URL_REPOSITORY "")
set(wwpcamera_DEPRECATED "")